# Generated by Django 3.1.2 on 2020-10-08 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birthdoay',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='data',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='has_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='info',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='momey',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='period_at',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='website_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
